#+TITLE: README - fogbugz-emacs
#+DATE: 10 November 2012

* License and COPYING
See [[file:COPYING][COPYING]] for license and copyright information.

* Org Mode Integration
fogbugz-emacs can be integrated with org-mode and that was the
original intention for creating fogbugz-emacs. Using properties it can
pull in more information about cases and construct a full list of
cases for a project.

* The Mock Server
fogbugz-emacs comes with a web server that simulates the FogBugz API.
This was created due to a lack of Internet when moving into a new
place. Another reason is that sometimes you can't do things live. At
work, it would be a problem to create multiple projects and cases
while working on fogbugz-emacs. Other users would see this and think
something is wrong.

A local mock server reduces latency to...basically no latency.

I tried to replicate as much functionality as possible. My reasoning
is that an interface to a web API is incomplete, and very very
optimistic, if it can only handle positive cases. It should be able to
handle the cases where something goes wrong.

The mock server is written in Common Lisp and has been tested with
SBCL on GNU/Linux. It uses the fantastic Hunchentoot web server
library and the CXML library to generate the XML output.

* Tasks
** fogbugz-emacs
*** TODO Login and logoff commands
Need to store a token
*** TODO List cases
*** TODO List projects
*** TODO Create case
** org-fogbugz
*** TODO Create case
Properties:
  - id
  - last-updated
  - creator
  - area

Tags are listed beside the item.

Assumes that the TODO statuses are setup the same way.
*** TODO Update case
Using a timestamp stored in the properties, Last-Updated or something
like that. Need to be able to force updating with a prefix argument.
** Mock Server

* Example Project:The Farm (expected output from org-fogbugz)
:PROPERTIES:
:ProjectId: a
:Owner: [[mailto:grandpa@oldmacdonald.com][Old MacDonald]] (555-294-4778)
:Group: Internal
:END:

This is the expected output from the org-fogbugz code.
** TODO Duck, Duck... but No Goose!						 :first:second:third:
:PROPERTIES:
:CaseId: 123
:OriginalTitle: Problem finding the goose...
:OpenedBy: [[mailto:grandpa@oldmacdonald.com][Old MacDonald]]
:Area: Pond
:Category: Feature
:Effort: 3 hours
:LastUpdated: 2012-11-11
:END:

(The TODO status is set when the case is open, when it's closed, the
status is switched to DONE)

(This is the latest text summary) I searched the docs, but no goose!

(There is no due date for this case, but if there were, it'd be used
for the DEADLINE)
